// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmJfiyfQOyJfy-vRTTncVuzZp6FCXTtTI',
    appId: '1:1058503553650:web:964ea642b8d2ad106dc8eb',
    messagingSenderId: '1058503553650',
    projectId: 'crashlytics-with-g10',
    authDomain: 'crashlytics-with-g10.firebaseapp.com',
    storageBucket: 'crashlytics-with-g10.appspot.com',
    measurementId: 'G-N3QC4BGWND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKaVvJDIQqwYDhR9YqVKEqt43O9O1ue-Y',
    appId: '1:1058503553650:android:8dd962ca8994f8ab6dc8eb',
    messagingSenderId: '1058503553650',
    projectId: 'crashlytics-with-g10',
    storageBucket: 'crashlytics-with-g10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiLrD19JbZxLYfVrmfqjIsaWQ-XSQ3TC4',
    appId: '1:1058503553650:ios:81445dec86e2c6db6dc8eb',
    messagingSenderId: '1058503553650',
    projectId: 'crashlytics-with-g10',
    storageBucket: 'crashlytics-with-g10.appspot.com',
    iosBundleId: 'com.pdp.learnAuthFirebaseG10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiLrD19JbZxLYfVrmfqjIsaWQ-XSQ3TC4',
    appId: '1:1058503553650:ios:81445dec86e2c6db6dc8eb',
    messagingSenderId: '1058503553650',
    projectId: 'crashlytics-with-g10',
    storageBucket: 'crashlytics-with-g10.appspot.com',
    iosBundleId: 'com.pdp.learnAuthFirebaseG10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmJfiyfQOyJfy-vRTTncVuzZp6FCXTtTI',
    appId: '1:1058503553650:web:9c5d1aaeed430aa26dc8eb',
    messagingSenderId: '1058503553650',
    projectId: 'crashlytics-with-g10',
    authDomain: 'crashlytics-with-g10.firebaseapp.com',
    storageBucket: 'crashlytics-with-g10.appspot.com',
    measurementId: 'G-F44QJDLSW1',
  );
}
